name: Production Deployment Pipeline

on:
  push:
    branches: [main, master]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: flask-backend
  IMAGE_TAG: ${{ github.sha }}
  EC2_SSH_USER: 'ubuntu'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code (simplified - no path parameter)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Debug: Verify file structure
      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Dockerfile exists at backend/: $(test -f backend/Dockerfile && echo 'YES' || echo 'NO')"
          ls -R

      # 3. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 4. Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 5. Build Docker image (corrected path)
      - name: Build Docker image
        run: |
          cd backend
          docker build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            .

      # 6. Vulnerability scan (non-blocking)
      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: 'table'
          severity: 'CRITICAL'
          ignore-unfixed: true

  deploy:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push to ECR
        run: |
          cd backend
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          ssh -i ~/.ssh/id_rsa ${{ env.EC2_SSH_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -ex
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d \
            --name flask-app \
            --restart unless-stopped \
            -p 5000:5000 \
            -v /home/ubuntu/app_data:/app/data \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker ps | grep flask-app || exit 1
          sleep 5
          curl -f http://localhost:5000 || exit 1
          EOF