name: Test Docker Build

on:
  push:
    branches: [ main, master ]  # Triggers on push to main/master
  pull_request:                # Optional: Also runs on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd backend  # Navigate to your backend folder
          docker build -t flask-app .
